### ISSUE TITLE
Doesn't work on files with unicode characters (\uXXXX)

### ISSUE THREAD

**Issue by j1warren** [Wazzaps/jqed#11]
When processing a big (>1024b) file with strings of unicode characters (\uXXXX) **jqed** errors out as such:

```
File "./jqed", line 86, in _jq_out_avail_cb
    chunk = os.read(self.jq_proc.stdout.fileno(), 1024).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 1023: unexpected end of data
```
I don't really know python, but I thought decoding blocks of 1024b might break those unicode characters in half.
So when changing 1024 to 100*1024 **jqed** then sometimes works, sometimes doesn't. And even when it works, entering '**.**' makes it die the same way, though on a different position.

I've uploaded a test.json.gz (50kB) to [https://easyupload.io/smkd7a](https://easyupload.io/smkd7a).

**Comment by Wazzaps** [comment]
Seems like I want to represent that as bytes, I'll try to fix it this week
