### ISSUE TITLE
Weird artifacts under WSL

### ISSUE THREAD

**Issue by PurpleMyst** [Wazzaps/jqed#6]
hi, jqed suffers from https://github.com/urwid/urwid/issues/264

could you implement the workaround?

**Comment by Wazzaps** [comment]
Looking into it! I'll need you for testing, I don't own a Windows machine

**Comment by PurpleMyst** [comment]
It doesn't produce artifacts now but it seems to chop off output. Here's what I mean:

1. [on start](https://files.catbox.moe/jtn1na.png)
2. [after typing](https://files.catbox.moe/jajwfb.png)

**Comment by Wazzaps** [comment]
This might be another bug (that I fixed in master), try to reproduce the chopped-off effect, then press up/down a couple of times. If that fixes it, then it will all be fixed once I merge.

**Comment by PurpleMyst** [comment]
Yep, if I press up it works.

**Comment by Wazzaps** [comment]
@PurpleMyst master should be good now

**Comment by PurpleMyst** [comment]
Perfect, thank you for your quick response @Wazzaps, very nice and helpful :)
